### ISSUE TITLE
Error in topoplotFast - Matrix dimensions must agree

### ISSUE THREAD

**Issue by chrichat** [sccn/ICLabel#7] opened 2020-04-29 16:47 UTC
Dear Sir/MAdam

I am facing an error while using IClabel
My code is straightforward

EEG=pop_biosig('edf.file');
EEG=pop_runica(EEG,'chanind',[1:22]);
EEG=icalabel(EEG);

And i receive the following error (probably due to the fact that i do not do ICA in all of the channels?) :

Error using  / 
Matrix dimensions must agree.

Error in topoplotFast (line 894)
squeezefac = rmax/plotrad;

Error in ICL_feature_extractor (line 33)
            topoplotFast(EEG.icawinv(:, it), EEG.chanlocs(EEG.icachansind), ...

Error in iclabel (line 52)
features = ICL_feature_extractor(EEG, flag_autocorr);

**Comment by lucapton** [comment] 2020-05-04 15:33
I loaded the sample data that comes with eeglab and then ran the last two lines of code as you wrote them (correcting icalabel to iclabel) and was not able to replicate your error. I'm using MATLAB 2019a, a freshly installed copy of EEGLAB, and the most updated version of ICLabel.  You could share your data with me or provide more information about what versions you're using or anything else you think might help. As it stands, I don't know what the problem is.

**Comment by lucapton** [comment] 2020-08-08 20:05
Closing this as it's been months.

**Closed as completed by lucapton** 2020-08-08 20:05 UTC
