### ISSUE TITLE
Is there a way to download the original dataset?

### ISSUE THREAD

**Issue by ghost** [sccn/ICLabel#9] opened 2020-06-11 22:34 UTC
Hi,

First of all, congratulations on this project! :)

I was wondering if the ICs + labels were also available to download. I have a few ideas for new features and would like to test them, but I would need the original ICs and their corresponding labels. I imagine it might be a huge dataset! Is there any way to access the original dataset?

Thanks!

**Comment by arnodelorme** [comment] 2020-06-16 14:05
@lucapton can the dataset be downloaded?

**Comment by lucapton** [comment] 2020-06-16 15:20
There is a dataset available but not with the raw IC time series. It includes labels and a number of extracted features from each component. If you look at my other repositories, it’s called ICLabel-dataset and includes a python class for loading and managing the dataset. You’ll have to then download a number of files containing the features and labels. I need to fix the documentation because the automatic downloads have been giving people issues.

**Comment by ghost** [comment] 2020-06-16 16:09
Hi, thanks for your responses. I already have the dataset with the labels and features (around 25GB), but in order to create new features I would need the raw IC time series. Are they available for download, or will they be available in the future?

**Comment by lucapton** [comment] 2020-06-16 16:24
I understand but unfortunately they are not available and likely will not be. The ICs were extracted from datasets on a living server so their current state is very different than they were originally. It was was in feasible at the time to make a full duplicate of the server for preservation. Furthermore, doing so may have violated any number of IRB guidelines as the datasets come from many different experiments, each with their own IRB agreement. 

I understand this is likely disappointing.

**Comment by ghost** [comment] 2020-06-16 16:40
Sure, it's perfectly understandable. Thanks, anyway. :)

**Closed as completed** 2020-06-16 16:45 UTC
